spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: alerts
    consumer:
      auto-offset-reset: earliest
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  mail:
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    username: mail
    password: pass
